name: linting
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  unit_test-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      - name: install modules
        run: npm i
      - name: linting typescript
        run: npm run lint:ts
        if: always()
      # - name: unit testing
      #   if: always()
      #   run: npm run test:unit
